steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/regrets-reporter-dev/myimage',
        '.',
      ]
logsBucket: 'gs://regrets-reporter-loggs-bucket'
    options:
      logging: GCS_ONLY

