steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/regrets-reporter-dev/myimage',
        '.',
      ]
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
